server:
  port: 8090

spring:
  application:
    name: service-app-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/service-app-realm/protocol/openid-connect/certs

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true

          routes:
            - id: member-request-service
              uri: lb://member-request-service
              predicates:
                  - Path=/member-request-service/**
              filters:
                  - name: RequestRateLimiter
                    args:
                      rate-limiter: "#{@defaultRateLimiter}"
                      key-resolver: "#{@userKeyResolver}"
                  - name: CircuitBreaker
                    args:
                      name: member-request-service-circuitbreaker
                      fallbackUri: forward:/fallback/member-request-service
                  - StripPrefix=1

            - id: member-service
              uri: lb://member-service
              predicates:
                - Path=/member-service/**
              filters:
                - name: RequestRateLimiter
                  args:
                    rate-limiter: "#{@defaultRateLimiter}"
                    key-resolver: "#{@userKeyResolver}"
                - name: CircuitBreaker
                  args:
                    name: member-service-circuitbreaker
                    fallbackUri: forward:/fallback/member-service
                - StripPrefix=1

            - id: pricing-service
              uri: lb://pricing-service
              predicates:
                - Path=/pricing-service/**
              filters:
                - name: RequestRateLimiter
                  args:
                    rate-limiter: "#{@defaultRateLimiter}"
                    key-resolver: "#{@userKeyResolver}"
                - name: CircuitBreaker
                  args:
                    name: pricing-service-circuitbreaker
                    fallbackUri: forward:/fallback/pricing-service
                - StripPrefix=1

springdoc:
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  swagger-ui:
    urls:
      - name: member-service
        url: /member-service/v3/api-docs
      - name: pricing-service
        url: /pricing-service/v3/api-docs
      - name: member-request-service
        url: /member-request-service/v3/api-docs

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,gateway,prometheus