apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-app-sa
  namespace: service-app
  labels:
    account: service-app

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-app-reader
  namespace: service-app
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "services", "endpoints", "configmaps"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-app-reader-binding
  namespace: service-app
subjects:
  - kind: ServiceAccount
    name: service-app-sa
    namespace: service-app
roleRef:
  kind: Role
  name: service-app-reader
  apiGroup: rbac.authorization.k8s.io