apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-request-service
  namespace: service-app
  labels:
    app: member-request-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member-request-service
  template:
    metadata:
      labels:
        app: member-request-service
    spec:
      serviceAccountName: service-app-sa
      containers:
        - name: member-request-service
          image: member-request-service:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: OTEL_SERVICE_NAME
              value: "member-request-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4318"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_TRACES_EXPORTER
              valueFrom:
                secretKeyRef:
                  name: service-app-secrets
                  key: OTEL_TRACES_EXPORTER
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/app/agents/opentelemetry-javaagent.jar"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-app-secrets
                  key: REDIS_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8084
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
              ephemeral-storage: "256Mi"
            limits:
              memory: "1Gi"
              cpu: "1000m"
              ephemeral-storage: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: member-request-service
  namespace: service-app
spec:
  selector:
    app: member-request-service
  ports:
    - port: 8084
      targetPort: 8084